apiVersion: v1
kind: Namespace
metadata:
  name: $namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
    env: $env
  name: hello
  namespace: $namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      env: $env
  strategy: {}
  template:
    metadata:
      labels:
        app: hello
        env: $env
    spec:
      containers:
      - image: $image
        name: istioproject
        ports:
        - containerPort: $port
---
kind: Service
apiVersion: v1
metadata:
  name: hello
  namespace: $namespace
  labels:
    app: hello
    env: $env
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: $port
      targetPort: $port
  selector:
    app: hello
    env: $env
  type: ClusterIP
  sessionAffinity: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: gitops-tst-route
  namespace: $namespace
  labels:
    app: hello
    env: $env
spec:
  path: /istio
  to:
    kind: Service
    name: hello
    weight: 100
  port:
    targetPort: $port-tcp
  wildcardPolicy: None
