apiVersion: apps/v1
kind: Deployment
metadata:
  name: $name
  namespace: $namespaces
spec:
  selector:
    matchLabels:
      app: $app
  replicas: 1
  template:
    metadata:
      labels:
        app: $app
    spec:
      containers:
        - name: $name
          image: quay.io/oktaysavdi/istioproject:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: $app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: $app
  type: ClusterIP
