replicaCount: 1

#namespace: gitops-dev

labels:
  app: hello

deployments:
  name: hello
  envName: env
  envValue: dev
  containerName: istio
  containerPort: 8080

images:
  image: quay.io/oktaysavdi/istioproject
  tag: latest

service:
  type: ClusterIP
  port: 8080
  name: 8080-tcp
  targetPort: 8080

route:
  targetPort: 8080

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

autoscaling:
  resources: cpu
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
